
# ------------------------------------------------------------------------
# install envoy reverse-proxy
# ------------------------------------------------------------------------
- name: install docker and docker-compose
  hosts: all
  gather_facts: no
  remote_user: ubuntu
  vars:
    path: /home/gpenaud/work/ecolieu/cagette
  tasks:
  - name: install docker packages
    remote_user: ubuntu
    become: yes
    package:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    tags:
    - docker

  - name: add docker s official GPG key
    remote_user: ubuntu
    become: yes
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
    - docker

  - name: verify that we have the key with the fingerprint
    remote_user: ubuntu
    become: yes
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
    - docker

  - name: set up the stable repository
    remote_user: ubuntu
    become: yes
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
    tags:
    - docker

  - name: install docker
    remote_user: ubuntu
    become: yes
    package:
      name: docker-ce
      state: present
      update_cache: yes
    tags:
    - docker

  - name: add remote "ubuntu" user to "docker" group
    remote_user: ubuntu
    become: yes
    user:
      name: ubuntu
      group: docker
      append: yes
    tags:
    - docker

  - name: install docker-compose
    remote_user: ubuntu
    become: yes
    get_url:
      url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      owner: ubuntu
      mode: 'u+x,g+x'
