
# ------------------------------------------------------------------------
# install envoy reverse-proxy
# ------------------------------------------------------------------------
- name: install ansible and molecule-compliant stack
  hosts: all
  gather_facts: no
  remote_user: ubuntu
  tasks:

  - name: wait for system to become reachable
    wait_for_connection:

  - name: create molecule directory
    remote_user: ubuntu
    file:
      state: directory
      path: /home/ubuntu/molecule
    when: skip_install is not defined or skip_install != "yes"

  - name: install python3 venv package
    remote_user: ubuntu
    become: yes
    package:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - python3.8-venv
    when: skip_install is not defined or skip_install != "yes"

  - name: create and activate venv, then install molecule packages
    remote_user: ubuntu
    shell: |-
      python3 -m venv molecule-venv
      source molecule-venv/bin/activate
      pip install "ansible"
      pip install "ansible-lint"
      pip install "docker"
      pip install "podman"
      pip install "molecule[lint]"
      pip install "molecule-docker"
      pip install "molecule-podman"
    args:
      executable: /bin/bash
      chdir: /home/ubuntu/molecule
    when: skip_install is not defined or skip_install != "yes"

  - name: copy molecule code to correct place
    remote_user: ubuntu
    copy:
      src: /home/gpenaud/work/ecolieu/ansible-role-cagette/cagette
      dest: /home/ubuntu/molecule/
