
# ------------------------------------------------------------------------
# upload source code
# ------------------------------------------------------------------------

- name: install requirements on cagette VM to AWS
  hosts: all
  gather_facts: no
  remote_user: ubuntu
  vars:
    path: /home/gpenaud/work/ecolieu/cagette
  tasks:
  - name: compress source code as an bz2 archive
    delegate_to: localhost
    community.general.archive:
      path:
      - "{{ path }}/*"
      dest: "{{ path }}/cagette.tar.bz2"
      exclude_path:
      - "{{ path }}/.git"
      - "{{ path }}/ansible"
      - "{{ path }}/terraform"
      format: bz2

  - name: unarchive cagette source code
    ansible.builtin.unarchive:
      src: "{{ path }}/cagette.tar.bz2"
      dest: /home/ubuntu

  - name: remove archive from remote
    ansible.builtin.file:
      path: "{{ path }}/cagette.tar.bz2"
      state: absent
