
# ------------------------------------------------------------------------------
# apache installation

# - name: "[install] - add apache2 packages"
#   become: yes
#   apt:
#     name: "{{ package }}"
#     update_cache: yes
#   loop:
#     - apache2
#     - libapache2-mod-neko
#   loop_control:
#     loop_var: package

# ------------------------------------------------------------------------------
# cagette installation

# - name: "[install] - add haxe packages required"
#   become: yes
#   npm:
#     name: "{{ package }}"
#     global: yes
#   loop:
#     - lix
#     - haxe-modular
#   loop_control:
#     loop_var: package

# - name: "[install] - create cagette group"
#   become: yes
#   group:
#     name: cagette
#
# - name: "[install] - create cagette user"
#   become: yes
#   user:
#     name: cagette
#     comment: system account for cagette webapp
#     group: cagette
#
# - name: "[install] - create cagette webapp directory"
#   file:
#     path: /var/www
#     state: directory
#     mode: 0755
#
# - name: "[install] - check for cagette source code presence"
#   stat:
#     path: /var/www/cagette
#   register: cagette_source
#   failed_when: no
#   changed_when: no
#
# - block:
#   - name: "[install] - download git source code"
#     become: yes
#     git:
#       repo: "https://github.com/gpenaud/cagette.git"
#       dest: /tmp/cagette
# #
#   - name: "[install] - copy source code to apache directory"
#     become: yes
#     copy:
#       src: /tmp/cagette/docker/app/
#       dest: /var/www/cagette
#       owner: cagette
#       group: cagette
#       remote_src: yes
#
#   - name: "[install] - remote git repository from /tmp"
#     become: yes
#     file:
#       path: /tmp/cagette
#       state: absent
#   when: not cagette_source.stat.exists or (force_source is defined and force_source == "yes")
