
- name: "[preflight] - include vars file"
  include_vars: vars/required_environment.yml

- name: "[preflight] - check environment variable presence"
  fail:
    msg: "Environment variable {{ env_var }} is not defined"
  when: env_var not in ansible_env
  loop: "{{ required_environment_vars }}"
  loop_control:
    loop_var: env_var
