# ------------------------------------------------------------------------------
# packages installation

- name: "[prepare] - add required apt packages"
  become: yes
  apt:
    name: "{{ package }}"
    update_cache: yes
  loop:
    - git
  loop_control:
    loop_var: package

# ------------------------------------------------------------------------------
# npm installation

- name: "[prepare] - check for npm command presence"
  shell: command -v npm >/dev/null 2>&1
  register: installed
  failed_when: no
  changed_when: no

- name: "[prepare] - get nodejs apt repository script"
  get_url:
    url: https://deb.nodesource.com/setup_17.x
    dest: /tmp/nodejs_17.sh
    mode: 'u+rwx'
  when: installed.rc != 0
  register: download

- name: "[prepare] - add nodejs apt repository"
  become: yes
  shell: /tmp/nodejs_17.sh
  when: download.changed

- name: "[prepare] - install npm package"
  become: yes
  apt:
    name: nodejs
    # update_cache: yes
  when: download.changed

- name: "[prepare] - remove nodejs installer script"
  file:
    path: /tmp/nodejs_17.sh
    state: absent
