version: "3.6"

networks:
  cagette:

volumes:
  database:

services:
  webapp:
    image: gpenaud/cagette-webapp
    build:
      context: .
      args:
        CAGETTE_SQL_LOG: "${CAGETTE_SQL_LOG:-}"
        CAGETTE_DEBUG: "${CAGETTE_DEBUG:-}"
        CAGETTE_CACHETPL: "${CAGETTE_CACHETPL:-}"
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
    networks:
      - cagette

  mailer:
    hostname: mailer
    image: gpenaud/cagette-mailer
    build:
      context: ./../cagette-mailer
    ports:
      - 5000
    environment:
      # mailer configuration
      MAILER_HOST: "0.0.0.0"
      # smtp relay configuration
      SMTP_HOST: "${CAGETTE_SMTP_HOST:-}"
      SMTP_PORT: "${CAGETTE_SMTP_PORT:-}"
      SMTP_USER: "${CAGETTE_SMTP_USER:-}"
      SMTP_PASSWORD: "${CAGETTE_SMTP_PASSWORD:-}"
    depends_on:
      - webapp
    networks:
      - cagette

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
      - ./services/mysql/dumps/:/root/dumps
      - ./services/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - cagette
