version: "3.2"

networks:
  cagette:

volumes:
  database:

services:
  cagette:
    image: gpenaud/cagette
    build:
      context: .
      args:
        CAGETTE_SMTP_HOST: "${CAGETTE_SMTP_HOST:-}"
        CAGETTE_SMTP_PORT: "${CAGETTE_SMTP_PORT:-}"
        CAGETTE_SMTP_USER: "${CAGETTE_SMTP_USER:-}"
        CAGETTE_SMTP_PASSWORD: "${CAGETTE_SMTP_PASSWORD:-}"
        CAGETTE_SQL_LOG: "${CAGETTE_SQL_LOG:-}"
        CAGETTE_DEBUG: "${CAGETTE_DEBUG:-}"
    # for debugging purposes
    volumes:
      - type: bind
        source: ./docker/app/js
        target: /var/www/cagette/js
      - type: bind
        source: ./docker/app/src
        target: /var/www/cagette/src
      - type: bind
        source: ./docker/app/devLibs/sugoi
        target: /var/www/cagette/devLibs/sugoi
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
    networks:
      - cagette

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - 3306
    volumes:
      - database:/var/lib/mysql
      - ./docker/mysql/dumps/:/root/dumps
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - cagette
