version: "3"

networks:
  cagette:

volumes:
  database:

services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
      - ./mysql/dumps/:/root/dumps
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - cagette

  cagette:
    build: .
    ports:
      - 80:80
    networks:
      - cagette
    depends_on:
      - mysql
