version: "3.2"

networks:
  cagette:

volumes:
  database:

services:
  cagette:
    image: gpenaud/cagette
    build:
      context: .
      args:
        CAGETTE_SQL_LOG: "${CAGETTE_SQL_LOG:-}"
        CAGETTE_DEBUG: "${CAGETTE_DEBUG:-}"
        CAGETTE_CACHETPL: "${CAGETTE_CACHETPL:-}"
    restart: always
    # for debugging purposes
    volumes:
      - type: bind
        source: ./docker/app/js
        target: /var/www/cagette/js
      - type: bind
        source: ./docker/app/src
        target: /var/www/cagette/src
      - type: bind
        source: ./docker/app/backend
        target: /var/www/cagette/backend
      - type: bind
        source: ./docker/app/devLibs/sugoi
        target: /var/www/cagette/devLibs/sugoi
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
    networks:
      - cagette

  mailer:
    hostname: mailer
    image: gpenaud/cagette-mailer
    build:
      context: ./../mailer
    ports:
      - 5000:5000
    environment:
      # mailer configuration
      MAILER_HOST: "0.0.0.0"
      # smtp relay configuration
      SMTP_HOST: "${CAGETTE_SMTP_HOST:-}"
      SMTP_PORT: "${CAGETTE_SMTP_PORT:-}"
      SMTP_USER: "${CAGETTE_SMTP_USER:-}"
      SMTP_PASSWORD: "${CAGETTE_SMTP_PASSWORD:-}"
    depends_on:
      - cagette
    networks:
      - cagette

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - 3306
    volumes:
      - database:/var/lib/mysql
      - ./docker/mysql/dumps/:/root/dumps
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - cagette
