apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-configuration
          mountPath: "/var/www/cagette/config.xml"
          subPath: "config.xml"
          readOnly: true
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-configuration
          mountPath: "/etc/apache2/sites-available/{{ .Values.vhost.name }}.conf"
          subPath: "vhost.conf"
        - name: {{ .Release.Name }}-{{ .Chart.Name }}-configuration
          mountPath: "/etc/apache2/sites-enabled/{{ .Values.vhost.name }}.conf"
          subPath: "vhost.conf"
          readOnly: true
      volumes:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}-configuration
        configMap:
          name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
          items:
          - key: "config.xml"
            path: "config.xml"
          - key: "vhost.conf"
            path: "vhost.conf"
