kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: scaleway
    kubernetes.io/tls-acme: "true"
    # add dns entry to traefik ingress controller ip
    kubernetes.io/ingress.class: traefik
    # external-dns.alpha.kubernetes.io/target: traefik.happynuts.me
spec:
  rules:
  - host: {{ .Values.vhost.name }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-{{ .Chart.Name }}-service
            port:
              number: 80
  tls:
  - hosts:
    - {{ .Values.vhost.name }}
    secretName: {{ .Values.vhost.name }}-cert
