kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-{{ .Chart.Name }}-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ExternalName
  externalName: {{ .Release.Name }}-{{ .Chart.Name }}-service.{{ .Values.namespace }}.svc.cluster.local
