apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Chart.Name }}-service
spec:
  clusterIP: None
  selector:
    app: {{ .Chart.Name }}-service
  ports:
    - name: tcp
      protocol: TCP
      port: 3306
