apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-statefulset
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ .Chart.Name }}-service
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-statefulset
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-statefulset
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: mysql
              protocol: TCP
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: ROOT_PASSWORD
                  name: {{ .Chart.Name }}-secret
          volumeMounts:
            - name: {{ .Chart.Name }}-data
              mountPath: "/var/lib/mysql"
            - name: {{ .Chart.Name }}-config
              mountPath: "/etc/mysql/conf.d"
              readOnly: true
      volumes:
        - name: {{ .Chart.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}-pvc
        - name: {{ .Chart.Name }}-config
          configMap:
            name: {{ .Chart.Name }}-configmap
            items:
            - key: "my.cnf"
              path: "my.cnf"
